[project]
name = "dj-sql-explorer"
version = "0.1.0"
description = "Django SQL Explorer example for django-redshift-backend"
readme = "README.md"
requires-python = ">=3.10, <4"
dependencies = [
    "django-environ==0.8.1",
    "django-redshift-backend",
    "django-sql-explorer",
    "python-dateutil>=2.9",
]

[tool.uv.sources]
django-redshift-backend = { path = "../..", editable = true }
